[google]
type = "service_account"
project_id = "tintos-lovers"
private_key_id = "1c0800ef26b4a99cd9479ff577779f7070f26363"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDEfRztpveDvFJ4
kFQD2BVJJ1emf60ggxaqxkzufekkW9Wl2ffG6rWIYDDmsK3zRNk7b7N0gvQq1MAa
hlI4IZb638fWet3Ql3jFlUcDtOUVRxAEXbs0kWxKAxJ3vzK7uasONOTTPHdJEyYm
/Sr/C2NIkVBFU5oGuis76gCp8Voru7IDK9WwJKcLIbbVoWg//JWsB1krfcN02pCx
pUwXqYJNGxS55HOqx0PQFUu5ti7k64DSvGRm3SCKIE8pUu6exNhSd+4hqEVn3eIJ
GCOo7CT8pGJglIfwxzAmMijBtU3B9CyXdHvjmxzx9QS3q6d8bPJDtej2wtFGaUae
0fp3LB1jAgMBAAECggEAD0XCR96ggobSyjg9r4bOML90Gqb15/8IdgGv3SHAS2kv
9BI7JiT8Mzt20ZeODcieMfZ+tmGvZNzgia9DGMXTnHBkchFeyGXdp03xFSKsY7kA
T7aRZIahKieO+evMn7bQyuvllV2vz+hDIOiwvN4/u1ZALQNQh5FU5vVLU+pEnf13
/MkkgkIwx0TSuNQjLzr2xuaffMS076V2Hg65HO/M5c5R/ID0gltErmNJn0YdG/+o
8W2AIQRs4SDio0tIkMGlVMs8ucHYeWbBvlBoy0rOiEYCttwtYs6T7T/YXNlrDr5l
M+j44EwtBW0uNVQ9/cDeM2mfAIwVKx2P4fVHLYjtUQKBgQDiJXlrxDN58o0PBMxv
7KdOB9vVCiLK1j/DLf0FZXFvaVyiijaJEHq+rvQROk4CeoHdy5TtRWYbiyHXLIPu
MM/yv0YxWabsUmxNXLUujfyO6n5Rz0gztBsjYPs0BlFTm6ZKlD118GY/JnXCF2KO
3Vkc/ZrZA5FYT4BdbteeiovyFwKBgQDebV65Wt7UxkheXDJX8VP5DIeqJ2BQJXg9
NJ0pQ4LcokAdaiEM6U+vKPifLk7tFqYYxX+ioC5BUyIPphJzgw2eMMQazxzgTt+u
wJTa/M2Foice5ZTinFwbdB0+rDl3RuWoALGBg5ZLkn9hDh7qfMKffJdfcfuc/M2f
Vh0UHnk6lQKBgA0fdZNOWFpcO9lCQwa/qdm6VQRgyTISCrMtyP/2KgX4DDsWYCHG
Bglop5sUUhCMwVp4hNTb8RfqE/WjjKhWxspkVRNqC2itQ8GdfpoL/Trh2qCusZbm
faio6QrUzwVWA+lR/tsILza86ZpwtvRpXdFz2fd74IRKYL2LQBHgIkzTAoGAQBj4
gSXErUBuvnKHN3yeHFkWB1zNjosduVWeLLP91CMVouRgnd3mTq3Z59VqfTxXpS/U
9kJ+0ehpGmVbT9pmZD3dZXRl9+YC49MvkmPjvizaZTb3zs4MZQTzIIp1DQBrUhzR
CmenOiP/fTKaiixl0ZwP6ztnrPfVMaOZQaD+gnkCgYBFkX2Yf0Ui9mcVw6MfKDK1
8Y9ThIga6lTc0o1/11Rd9EfxdYohYQOtrts/aiVJyyMtdtMT1MEa87ykKKvqnkF+
cZFZGFf+2ZkSoeb+iChN4QQSPlWGSoj0EqXOR5HAc9AY+7ZxJjyTAhycqX+Ph4KY
moiyLiBn3PtG8w5WDfg8kA==
-----END PRIVATE KEY-----"""
client_email = "streamlit-access@tintos-lovers.iam.gserviceaccount.com"
client_id = "108706237262301560281"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-access%40tintos-lovers.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

[cloudinary]
cloud_name = "dm4lrkmuv"
api_key = "339348758796392"
api_secret = "NU1Pw8zpmSDRc-Okpov5cxM8Ii8"